services:
  app1:
    build: ./backend
    environment:
      - PORT=3000
  app2:
    build: ./backend
    environment:
      - PORT=3001
  app3:
    build: ./backend
    environment:
      - PORT=3002
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  haproxy:
    image: haproxy:latest
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
